### ISSUE TITLE
ArchLinux上で`sbt textBuildHtml`を行うと例外が出る

### ISSUE THREAD

**Issue by aiya000** [dwango/scala_text#218]
# 問題
ArchLinux上で`sbt textBuildHtml`を行うと、以下の例外が発生します。

```console
$ sbt textBuildHtml
.
.
.
[tut] compiling: /home/aiya000/Repository/scala_text/src/future-and-promise.md
Installing GitBook 3.1.1
java.lang.RuntimeException: Nonzero exit code: 139
        at scala.sys.package$.error(package.scala:27)
        at sbt.Streamed$.sbt$Streamed$$next$1(ProcessImpl.scala:429)
        at sbt.Streamed$$anonfun$sbt$Streamed$$next$1$1.apply(ProcessImpl.scala:430)
        at sbt.Streamed$$anonfun$sbt$Streamed$$next$1$1.apply(ProcessImpl.scala:430)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.foreach(Stream.scala:548)
        at NpmCliBase$class.printRun(NpmCliBase.scala:33)
.
.
.
```

# インストールしたArch用パッケージ
- sbt
- npm

```console
$ sbt
[info] Set current project to aiya000 (in build file:/home/aiya000/)
> about
[info] This is sbt 0.13.12
[info] The current project is {file:/home/aiya000/}aiya000 0.1-SNAPSHOT
[info] The current project is built against Scala 2.10.6
[info] Available Plugins: sbt.plugins.IvyPlugin, sbt.plugins.JvmPlugin, sbt.plugins.CorePlugin, sbt.plugins.JUnitXmlReportPlugin
[info] sbt, sbt plugins, and build definitions are using Scala 2.10.6
```

```console
$ npm --version
3.10.6
```

- - -

　私の環境の問題？  
以下、`sbt textBuildHtml`実行時の全ての出力です。

```console
$ sbt textBuildHtml
[info] Loading project definition from /home/aiya000/Repository/scala_text/project
[info] Loading project definition from /home/aiya000/Repository/scala_text/src/example_projects/trait-example/project
[info] Loading project definition from /home/aiya000/Repository/scala_text/src/example_projects/trait-refactored-example/project
[info] Set current project to textbook (in build file:/home/aiya000/Repository/scala_text/)
[info] Running tut.TutMain /home/aiya000/Repository/scala_text/src /home/aiya000/Repository/scala_text/gitbook .*\.(md|markdown|txt|htm|html)
[tut] compiling: /home/aiya000/Repository/scala_text/src/error-handling.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/sbt-compile-execute.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/class.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/implicit.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/sbt-install.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/test.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/case-class-and-pattern-matching.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/exercises.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/advanced-trait-di.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/control-syntax.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/trait.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/introduction-to-scala.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/SUMMARY.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/type-parameter.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/object.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/java-interop.md
Hello, World!
[tut] compiling: /home/aiya000/Repository/scala_text/src/INTRODUCTION.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/function.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/typeclass.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/basic.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/IDE.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/collection.md
[tut] compiling: /home/aiya000/Repository/scala_text/src/future-and-promise.md
Installing GitBook 3.1.1
java.lang.RuntimeException: Nonzero exit code: 139
        at scala.sys.package$.error(package.scala:27)
        at sbt.Streamed$.sbt$Streamed$$next$1(ProcessImpl.scala:429)
        at sbt.Streamed$$anonfun$sbt$Streamed$$next$1$1.apply(ProcessImpl.scala:430)
        at sbt.Streamed$$anonfun$sbt$Streamed$$next$1$1.apply(ProcessImpl.scala:430)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1085)
        at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1077)
        at scala.collection.immutable.Stream.foreach(Stream.scala:548)
        at NpmCliBase$class.printRun(NpmCliBase.scala:33)
        at GitBook$.printRun(GitBook.scala:5)
        at GitBook$$anonfun$buildBook$1$$anonfun$apply$2$$anonfun$apply$1.apply$mcV$sp(GitBook.scala:18)
        at GitBook$$anonfun$buildBook$1$$anonfun$apply$2$$anonfun$apply$1.apply(GitBook.scala:16)
        at GitBook$$anonfun$buildBook$1$$anonfun$apply$2$$anonfun$apply$1.apply(GitBook.scala:16)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:44)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:237)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (scalatext/*:textBuildHtml) Nonzero exit code: 139
[error] Total time: 192 s, completed 2016/09/18 4:01:18
```

**Comment by xuwei-k** [comment]
tut終わった後のgitbook生成部分(sbtから外部プロセス呼び出し)でエラーになってるみたいですが、上記のログだけだと失敗原因わからないので、sbtでtut実行後に以下のあたり

https://github.com/dwango/scala_text/blob/3a8c1c299ab6ac4275a10f90acba52654c7ecdb6/project/GitBook.scala#L18

に相当するコマンドを、sbt経由ではなく直接実行して、どういうログ出るか試してもらえますか？

**Comment by aiya000** [comment]
実行されているコマンドを確認した後、実行したらこんなんなってました…。

```cosole
$ node_modules/.bin/gitbook  build . gitbook/_book --gitbook=3.1.1
Installing GitBook 3.1.1
zsh: segmentation fault (core dumped)  node_modules/.bin/gitbook build . gitbook/_book --gitbook=3.1.1
```

**Comment by matsu-chara** [comment]
gitbookのinstallで落ちてそう・・ですね。 
関連しそうなissueがありました。 https://github.com/GitbookIO/gitbook-cli/issues/12

とはいえnodeのバージョンを上げたりとかしか手立てが思いつかないです(segmentation faultなので違いそうですが・・）

**Comment by aiya000** [comment]
うーん、流石にgitbookの方のIssueだとこちらはどうしようもないですよね…。
各コマンドのバージョンを記録しつつ、Closeしておきます。
```console
$ node --version
v6.5.0
$ npm version
{ scala_text: '1.0.0',
  npm: '3.10.6',
  ares: '1.10.1-DEV',
  http_parser: '2.7.1',
  icu: '57.1',
  modules: '48',
  node: '6.5.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.1.281.81',
  zlib: '1.2.8' }
$ gitbook version
CLI version: 2.3.0
GitBook version: 2.6.6
```
ありがとうございます :smile:
