### ISSUE TITLE
masterのtravis-ciでのビルドが壊れている

### ISSUE THREAD

**Issue by xuwei-k** [dwango/scala_text#301]
https://travis-ci.org/dwango/scala_text/builds/276749443

```
error: error while generating page "advanced-trait-di.md": 
InstallRequiredError: "svgexport" is not installed.
Install it using: "npm install svgexport -g"
[error] java.lang.RuntimeException: Nonzero exit code: 1
[error] 	at scala.sys.package$.error(package.scala:27)
[error] 	at scala.sys.process.BasicIO$Streamed$.next$1(BasicIO.scala:49)
[error] 	at scala.sys.process.BasicIO$Streamed$.$anonfun$apply$1(BasicIO.scala:50)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1169)
[error] 	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1159)
[error] 	at scala.collection.immutable.Stream.foreach(Stream.scala:531)
[error] 	at NpmCliBase.printRun(NpmCliBase.scala:34)
[error] 	at NpmCliBase.printRun$(NpmCliBase.scala:33)
[error] 	at GitBook$.printRun(GitBook.scala:6)
[error] 	at GitBook$.$anonfun$buildBook$3(GitBook.scala:19)
[error] 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[error] 	at sbt.std.Transform$$anon$3.$anonfun$apply$2(System.scala:44)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (scala_text/*:textBuildEpub) Nonzero exit code: 1
```

**Comment by xuwei-k** [comment]
エラーメッセージのとおりに svgexport を明示的にインストールしたらいける？(試してる最中)

**Comment by xuwei-k** [comment]
関係ない(?)が、別の警告でているので貼り付け

```
npm WARN deprecated babel-preset-es2015@6.18.0: We're super 😸  excited that you're trying to use ES2015 syntax, but instead of making more yearly presets 😭 , Babel now has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. preset-env without options will compile ES2015+ down to ES5 just like using all the presets together and thus is more future proof. It also allows you to target specific browsers so that Babel can do less work and you can ship native ES2015+ to user 😎 ! We are also in the process of releasing v7, so please give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and help test it out in beta! Thanks so much for using Babel 🙏, please give us a follow on Twitter @babeljs for news on Babel, join slack.babeljs.io for discussion/development and help support the project at opencollective.com/babel
npm WARN prefer global npm@3.7.5 should be installed with -g
```
